
import { Metadata } from "next";
import Sidebar from "./DocsSidebar";

export const metadata: Metadata = {
  title: "Shadlc UI - A light weight ui library",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`min-h-screen  flex items-center justify-end w-full`}>
      <Sidebar />
      {children}
    </div>
  );
}
